### ISSUE TITLE
自己加了部分功能

### ISSUE THREAD

**Issue by chi111i** [Macr0phag3/parselmouth#2]
通过百度网盘分享的文件：parselmouth.zip
链接：https://pan.baidu.com/s/1TfhdM92byaYNMnfJrOP-zA?pwd=6861 
提取码：6861 
您好，根据您的项目我简单的加了点功能，希望你采纳优化一下。我算法太菜了

**Comment by Macr0phag3** [comment]
@chi111i 十分感谢，代码我已经收到了，看着得抽时间优化一下。不过既然都用 github了，其实你可以尝试提个 pull request，用度盘还是有点。。
